### ISSUE TITLE
Question about use case with nginx ingress

### ISSUE THREAD

**Issue by xmclark** [inlets/inlets#105]
# Problem

I am attempting to use a [pod running in GCP kube ☁️ as my inlets exit node](https://github.com/alexellis/inlets#use-your-kubernetes-cluster-as-an-exit-node) in  and a raspberry pi running inlets client that lives at my house 🏡. I am getting websocket bad handshake messages from my client like this:

`ERRO[0000] Failed to connect to proxy error="websocket: bad handshake"`

# Context/Setup

My kubernetes cluster is running the [nginx-ingress controller](https://github.com/kubernetes/ingress-nginx). All HTTP (port 80) and HTTPS (port 443) traffic is routed to a a L4 load balancer with a static IP. I am running a typical configuration with nginx-ingress controller. The only modification I made was to set the LoadBalancer IP to the one I created with GCP.

In my example I will obscure my actual domain as `inlets.example.com`. I know that I own this domain, and I can serve traffic from typical web services with aan nginx-ingress and cert-manager TLS setup, no problem.

I have a deployment running an inlets server:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets
spec:
  selector:
    matchLabels:
      app: inlets
  replicas: 1
  template:
    metadata:
      labels:
        app: inlets
    spec:
      containers:
        - name: inlets
          image: alexellis2/inlets:2.3.2
          imagePullPolicy: Always
          command: ["inlets"]
          args:
            - "server"
            - "--print-token=true"
            - "--token=MY_TOKEN"
```

I can see that inlets server exposes on port 8000 by default.

I would like to port forward through my service like so:

```
apiVersion: v1
kind: Service
metadata:
  name: inlets
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: inlets
```

Then my ingress can just be this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inlets
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - inlets.example.com
      secretName: inlets-tls
  rules:
    - host: inlets.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: inlets
              servicePort: 80
```

My raspberry pi has a server running on port 80. I run this command to create the client:
`inlets client --remote=inlets.example.com --upstream=http://127.0.0.1:80 --token MY_TOKEN`

This gets displayed on loop:
```
INFO[0000] Connecting to proxy                           url="ws://inlets.example.com/tunnel"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
```

## Expected Behaviour
I expected that port forwarding should not be a problem. 

`internet -> 80 <-> ingress <-> 80 <-> Service <-> 8000 <->exit node ------ client <-> 80 <-> app`

The message "websocket: bad handshake" is a little confusing, and I'm not sure what else I can try. I know that I can create a VM or standalone LB, but I was hoping to get this particular setup working because the nginx-ingress controller makes it convenient to standup new public facing services.

## Your Environment

Inlets running on raspberry pi client:
* inlets version `inlets --version` 
Version: 2.5.0
Git Commit: 9744ca87b0b0e4c32ce22aa102827d684f5ef792

* Inlets running in kube (alexellis2/inlets:2.3.2)
Version: dev
Git Commit: 6a245d9aab7d6a7c0faf1de54e52f99cf932108f

* Docker/Kubernetes version `docker version` / `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows
