### ISSUE TITLE
Support request on using privileged ports

### ISSUE THREAD

**Issue by geertvanheusden** [inlets/inlets#156]
## Expected Behaviour
When using the following docker-compose file I would expect the inlets server to be available on port 80 on the docker host:

```
version: '2'
services:
  inlets:
    image: inlets/inlets:2.6.3
    command: server --port=80 --token="internal"
    ports:
     - "80:80"
```

## Current Behaviour
The container will not start and shows the following logs:

```
inlets_1  | 2020/02/05 09:09:06 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
inlets_1  | 2020/02/05 09:09:06 Starting server - version 2.6.3
inlets_1  | 2020/02/05 09:09:06 Server token: "internal"
inlets_1  | 2020/02/05 09:09:06 Control Plane Listening on :80
inlets_1  | 2020/02/05 09:09:06 Data Plane Listening on :80
inlets_1  | 2020/02/05 09:09:06 listen tcp :80: bind: permission denied
```

Specifying port 8080 for the inlets server and mapping it to port 80 on the host does work. The  [Dockerfile](https://github.com/inlets/inlets/blob/master/Dockerfile#L31) specifies port 80 so if it's not allowed to use this port, it might be confusing to specify it over here.

## Possible Solution
As mentioned above, a workaround could be to use the following config:

```
version: '2'
services:
  inlets:
    image: inlets/inlets:2.6.3
    command: server --port=8080 --token="internal"
    ports:
     - "80:8080"
```

## Steps to Reproduce (for bugs)
Copy the docker-compose file above to reproduce the bug.

## Your Environment
* OS: Debian 9.2
* Inlet docker image version 2.6.3, 
* Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
