### ISSUE TITLE
Technical support request

### ISSUE THREAD

**Issue by manuschillerdev** [inlets/inlets#183]
I use inlets to make local dev-servers available to the internet via kubernetes.

My config (note: dev-playground.mydomain.tld was changed since I don't want the URL to be public here).

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets
  template:
    metadata:
      labels:
        app: inlets
    spec:
      containers:
        - name: inlets
          image: inlets/inlets:2.6.3
          imagePullPolicy: Always
          command: ["inlets"]
          args:
            - "server"
            - "--token=abcdefg"
---
apiVersion: v1
kind: Service
metadata:
  name: inlets
  labels:
    app: inlets
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: inlets
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tec-138
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: dev-playground.mydomain.tld
      http:
        paths:
          - backend:
              serviceName: inlets
              servicePort: 8000
  tls:
    - hosts:
        - dev-playground.mydomain.tld
      secretName: cert01-tls
```
I then connect to my exit node with:
```
inlets client --remote=wss://dev-playground.mydomain.tld --upstream=http://localhost:3000 --token=abcdefg
```

That works fine for a lot of apps, even with hotreloading enabled (e.g. for `npx create-next-app`)

But: 

If I create a Vue App with:
```
npx @vue/cli create --default example-vue-app
```

and expose it
```
inlets client --remote=wss://dev-playground.mydomain.tld --upstream=http://localhost:8080 --token=abcdefg
```

I get the following error:
```
Invalid Host header
```

I can fix this by turning off host checks in webpack:
```
module.exports = {
    devServer: {
        disableHostCheck: true
    }
}
```

But then, I get a hotreloading error:
```
https://192.168.5.165:8080/sockjs-node/info?t=1591599504450 net::ERR_SSL_PROTOCOL_ERROR
```

When I try to map the IP as well:
```
inlets client --remote=wss://dev-playground.mydomain.tld --upstream="http://localhost:8080,https://192.168.5.165:8080" --token=abcdefg
```

I get this error:
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'dev-playground.mydomain.tld/'
```

## Expected Behaviour
I can tunnel local dev setups without modifying the local setups.

## Current Behaviour
As described before

## Possible Solution
No idea ..

## Steps to Reproduce (for bugs)
1. deploy the config above with adapted host information
2. create vue app locally: `npx @vue/cli create --default example-vue-app`
3. exose the local dev server `inlets client --remote=wss://dev-playground.mydomain.tld --upstream=http://localhost:8080 --token=abcdefg
`
4. try to access the app and see the different errors as described above

## Context

I want to have a "generic" tunnel, that can expose any local dev setup.

## Your Environment

* inlets version `inlets --version` 
Version: 2.7.3
Git Commit: 2934c3c247ea28996ebb50889403befced94b29a

* Docker/Kubernetes version `docker version` / `kubectl version`:
Client Version: v1.18.2
Server Version: v1.17.5

* Operating System and version (e.g. Linux, Windows, MacOS):
Mac Catalina latest & Ubuntu

* Link to your project or a code example to reproduce issue:
as above, can create an example repo if you like

I have no idea how to debug this any further so any input is highly appreciated :)
